# Generated by Django 2.1.2 on 2018-10-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20181015_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='creation_block',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grant',
            name='last_block_synced',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
