# Generated by Django 2.1.2 on 2018-12-16 22:16

from django.db import migrations


def migrate_avatars(apps, schema_editor):
    """Handle data migration"""
    profile_model = apps.get_model('dashboard', 'Profile')
    avatar_model = apps.get_model('avatar', 'Avatar')
    profiles = profile_model.objects.all()
    for profile in profiles:
        if profile.avatar:
            avatar = avatar_model.objects.filter(pk=profile.avatar.pk).first()
            avatar.profile = profile
            avatar.active = True
            avatar.save()


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_auto_20181216_2202'),
    ]

    operations = [
        migrations.RunPython(migrate_avatars),
    ]
