# Generated by Django 2.1.2 on 2018-12-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0127_auto_20181216_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
